#####################################
#                                   #
#        TopShop - By Sciirof       # 
#            version: 1.0           #
#                                   #
#####################################

#Shop GUI title you can use color codes
shopTitle: "&d&lTopShop&r&7 - Weclome"
removeTitle: "&d&lTopShop&r&7 - Remove" # Title admins see when removing items